on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
            - name: Get Actions user id
              id: get_uid
              run: |
                actions_user_id=`id -u $USER`
                echo $actions_user_id
                echo "uid=$actions_user_id" >> $GITHUB_OUTPUT
            - name: Correct Ownership in GITHUB_WORKSPACE directory
              uses: peter-murray/reset-workspace-ownership-action@v1
              with:
               user_id: ${{ steps.get_uid.outputs.uid }}
            - uses: actions/checkout@master
            - name: Sync Wiki
              uses: joeizzard/action-wiki-sync@master
              with:
                username: lillywho
                access_token: ${{ secrets.GITHUB_TOKEN }}
                wiki_folder: wiki
                commit_username: 'lillywho'
                commit_email: 'lillywho@users.noreply.github.com'
                commit_message: 'action: wiki sync'
