on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Wiki Sync (fixed)
              uses: LillyWho/ghaction-wiki-sync-custom@v1.0
              with:
                username: lillywho
                access_token: ${{ secrets.GITHUB_TOKEN }}
                wiki_folder: wiki
                commit_username: 'lillywho'
                commit_email: 'lillywho@users.noreply.github.com'
                commit_message: 'action: wiki sync'
